#server.error.whitelabel.enabled=false
spring.main.banner-mode=off
logging.level.org.springframework=ERROR
server.port=8099
#spring.jpa.hibernate.ddl-auto=create

#spring.datasource.initialization-mode=always
#spring.sql.init.platform=postgres
#spring.datasource.url=jdbc:postgresql://192.168.0.33:5432/postgres
#spring.datasource.username=posgres
#spring.datasource.password=1
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:oracle:thin:@172.16.0.32:1521/frb
spring.datasource.username=frbdis
spring.datasource.password=f
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
server.error.include-message=always
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
